CHECKLIST_FIELDS = ['taxId', 'organism part', 'lifestage', 'project name',
                    'collected by', 'collection date',
                    'geographic location (country and/or sea)',
                    'geographic location (latitude)',
                    'geographic location (longitude)',
                    'geographic location (region and locality)',
                    'identified by', 'habitat', 'identifier_affiliation',
                    'sex', 'collecting institution', 'GAL', 'specimen voucher',
                    'specimen id', 'GAL_sample_id', 'organism',
                    'geographic location (depth)',
                    'geographic location (elevation)', 'sample derived from',
                    'relationship', 'culture or strain id']

projects = [
            # ['PRJNA489245', 'Bat1K Project']]
            #  ['PRJNA720569', 'The California Conservation Genomics Project (CCGP)']]
            # ['PRJNA734913', 'Amphibalanus amphitrite(Genome Sequencing and assembly)']]
            # ['PRJDB6260', 'Elasmobranch shark genome evolution']]
            # ['PRJEB43510', 'ERGA']]
            # ['PRJEB40665', 'DToL']]
            # ['PRJNA163993', 'i5k initiative'],
            # ['PRJNA293101', 'Orestias ascotanensis Genome sequencing and assembly'],
            # ['PRJNA489243', 'Vertebrate Genomes Project'],
            # ['PRJNA512907', 'DNA Zoo'],
            # ['PRJNA682446',
            #  'Genome sequencing data and assemblies generated by the Lewin Lab @ UC Davis Genome Center.']]
            # ['PRJNA813333', 'Canadian BioGenome Project (CBP)']]
            # ['PRJEB51690', 'Anopheles Reference Genomes Project (Data and assemblies)']]
            # ['PRJNA312960', '200 Mammals']]
            # ['PRJNA634441', 'Monomorium pharaonis Genome sequencing and assembly'],
            # ['PRJNA649812', 'The Global Invertebrate Genomics Alliance (GIGA) genomes and transcriptomes'],
             ['PRJEB43743', 'ASG']]
            # ['PRJNA844590', 'Illinois EBP Pilot'],
            # ['PRJEB49670', 'Catalan Initiative for the Earth BioGenome Project (CBP)']]
            # ['PRJEB33226', '25 Genomes Project (Genome Data and Assemblies)']]
            # ['PRJNA545868', 'Bird 10,000 Genomes (B10K) Project - Family phase'],
            # ['PRJNA555319', 'USDA Agricultural Research Service’s Ag100Pest Initiative'],
            # ['PRJNA712951', 'ENDEMIXIT']]
            # ['PRJNA811786', 'African BioGenome Project (AfricaBP)'],
            # ['PRJNA707235', 'University of California Consortium for the Earth BioGenome Project (Cal-EBP)'],
            # ['PRJNA707598', 'Squalomix (genome sequencing and assembly of chondrichthyans)'],
            # ['PRJNA706690', 'CanSeq150 Project (Genome Data and Assemblies)']]
            # ['PRJNA706923', 'LOEWE Centre for Translational Biodiversity Genomics (LOEWE-TBG)']]
