apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: organisms-geolocation
  namespace: cron
spec:
  schedule: '20 23 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: organisms-geolocation
              image: ktibrahim/organisms-geolocation:latest
              command: [ "python3", "organisms-geolocation.py" ]
          restartPolicy: OnFailure