kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-pvc
  namespace: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default-cinder