apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cron-pv-claim
  namespace: cron
spec:
  storageClassName: default-cinder
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi