apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: mysql
spec:
  storageClassName: default-cinder
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi