apiVersion: v1
kind: Service
metadata:
    name: neo4j-np
    namespace: neo4j
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 30074
        targetPort: 7474
        name: http
      - protocol: TCP
        port: 30073
        targetPort: 7473
        name: https
      - protocol: TCP
        port: 30087
        targetPort: 7687
        name: bolt
    selector:
      app: neo4j-db