apiVersion: v1
kind: Service
metadata:
  name: elasticcron
  namespace: cron
spec:
  externalName: elasticsearch.elasticsearch.svc.cluster.local
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  type: ExternalName