apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: cron
spec:
  externalName: neo4j.neo4j.svc.cluster.local
  ports:
  - port: 30087
    protocol: TCP
    targetPort: 30087
  type: ExternalName